name: Automatic Reservations on PlayByPoint
on:
  schedule:
    - cron: '*/5 * * * *'  # Every day at 7am PST
  workflow_dispatch:     # Optional: lets you run it manually too

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        run: npx playwright test
        env:
          MY_USERNAME: ${{ secrets.MY_USERNAME }}
          PASSWORD: ${{ secrets.PASSWORD }}

      - name: Upload videos
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-videos
          path: playwright-report/data/**/*.webm

      - name: Upload full Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-html-report
          path: playwright-report/
